=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::ApiKeysApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApiKeysApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::ApiKeysApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiKeysApi' do
    it 'should create an instance of ApiKeysApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::ApiKeysApi)
    end
  end

  # unit tests for create_api_key_api_v1_api_keys_post
  # Create Api Key
  # @param api_key_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyCreateResponse]
  describe 'create_api_key_api_v1_api_keys_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_api_key_api_v1_api_keys_api_key_id_get
  # Get Api Key
  # @param api_key_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyDetailResponse]
  describe 'get_api_key_api_v1_api_keys_api_key_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_api_keys_api_v1_api_keys_get
  # List Api Keys
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyListResponse]
  describe 'list_api_keys_api_v1_api_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_api_key_api_v1_api_keys_api_key_id_patch
  # Patch Api Key
  # @param api_key_id 
  # @param api_key_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyDetailResponse]
  describe 'patch_api_key_api_v1_api_keys_api_key_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_api_key_api_v1_api_keys_api_key_id_delete
  # Revoke Api Key
  # @param api_key_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyRevokeResponse]
  describe 'revoke_api_key_api_v1_api_keys_api_key_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_api_key_api_v1_api_keys_api_key_id_rotate_post
  # Rotate Api Key
  # Revoke the existing key and create a new one with the same name.
  # @param api_key_id 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyRotateResponse]
  describe 'rotate_api_key_api_v1_api_keys_api_key_id_rotate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
