=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::BatchesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BatchesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::BatchesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BatchesApi' do
    it 'should create an instance of BatchesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::BatchesApi)
    end
  end

  # unit tests for cancel_batch
  # Cancel Batch
  # Stop a batch that has not finished.  Items not yet started are cancelled. An item already rendering completes — the work is done and cancelling it would waste it.
  # @param batch_id 
  # @param [Hash] opts the optional parameters
  # @return [BatchResponse]
  describe 'cancel_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_batch
  # Create Batch
  # Queue many documents to be rendered at once.  Returns &#x60;202&#x60; — the batch is recorded and a worker renders it; nothing is rendered inside this request. Poll &#x60;get_batch&#x60; for progress, then &#x60;download_batch&#x60; for the results.  The whole batch is refused if it would exceed the monthly quota, rather than rendering part of it.
  # @param batch_create_request 
  # @param [Hash] opts the optional parameters
  # @return [BatchResponse]
  describe 'create_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for download_batch
  # Download Batch
  # Every completed render in the batch, as a ZIP.  &#x60;409&#x60; until the batch is &#x60;completed&#x60;. Items that failed are simply absent, so check &#x60;failed_items&#x60; rather than counting files.
  # @param batch_id 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'download_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_batch
  # Get Batch
  # A batch&#39;s status and its per-item counts.  The poll surface: &#x60;total_items&#x60;, &#x60;completed_items&#x60; and &#x60;failed_items&#x60; say how far it has got without listing every item.
  # @param batch_id 
  # @param [Hash] opts the optional parameters
  # @return [BatchResponse]
  describe 'get_batch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_batch_items
  # List Batch Items
  # Every item in a batch with its own status, newest first.  Where to look when &#x60;failed_items&#x60; is not zero: each row carries its error and, once rendered, its &#x60;render_id&#x60;.
  # @param batch_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [BatchItemsListResponse]
  describe 'list_batch_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_batches
  # List Batches
  # Batch jobs on this account, newest first.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [BatchesListResponse]
  describe 'list_batches test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
