=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::BrandingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BrandingApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::BrandingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrandingApi' do
    it 'should create an instance of BrandingApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::BrandingApi)
    end
  end

  # unit tests for delete_logo_api_v1_branding_logo_delete
  # Delete Logo
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_logo_api_v1_branding_logo_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_branding_api_v1_branding_get
  # Get Branding
  # @param [Hash] opts the optional parameters
  # @return [BrandingResponse]
  describe 'get_branding_api_v1_branding_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_branding_api_v1_branding_put
  # Update Branding
  # @param branding_update_request 
  # @param [Hash] opts the optional parameters
  # @return [BrandingResponse]
  describe 'update_branding_api_v1_branding_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_logo_api_v1_branding_logo_post
  # Upload Logo
  # @param file 
  # @param [Hash] opts the optional parameters
  # @return [BrandingResponse]
  describe 'upload_logo_api_v1_branding_logo_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
