=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::BusinessProfilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessProfilesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::BusinessProfilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessProfilesApi' do
    it 'should create an instance of BusinessProfilesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::BusinessProfilesApi)
    end
  end

  # unit tests for create_business_profile
  # Create Business Profile
  # Create an identity to issue documents as: the seller side.  &#x60;legal_name&#x60;, &#x60;tax_id&#x60;, address and bank details are what appears as the issuer, and what an e-invoicing ruleset checks. Distinct from a branding profile, which sets colours and a logo and says nothing about who you are.
  # @param business_profile_create 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [BusinessProfileResponse]
  describe 'create_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_business_profile
  # Delete Business Profile
  # Remove a business profile.  &#x60;409&#x60; if any document was issued under it, naming what still points at it.
  # @param business_profile_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_profile
  # Get Business Profile
  # One business profile.
  # @param business_profile_id 
  # @param [Hash] opts the optional parameters
  # @return [BusinessProfileResponse]
  describe 'get_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_business_profiles
  # List Business Profiles
  # The identities you issue documents *as*, newest first.  One per entity you bill from — a business with two trading names or two tax registrations needs two. For how documents *look* rather than who issues them, see the branding profiles.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [BusinessProfilesListResponse]
  describe 'list_business_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_business_profile
  # Update Business Profile
  # Change a business profile.  Only the fields you send are changed. Documents already issued keep the issuer details they carried at the time.
  # @param business_profile_id 
  # @param business_profile_patch 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [BusinessProfileResponse]
  describe 'update_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
