=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::BusinessProfilesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessProfilesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::BusinessProfilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessProfilesApi' do
    it 'should create an instance of BusinessProfilesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::BusinessProfilesApi)
    end
  end

  # unit tests for create_business_profile
  # Create Business Profile
  # @param business_profile_create 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [BusinessProfileResponse]
  describe 'create_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_business_profile
  # Delete Business Profile
  # @param business_profile_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_profile
  # Get Business Profile
  # @param business_profile_id 
  # @param [Hash] opts the optional parameters
  # @return [BusinessProfileResponse]
  describe 'get_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_business_profiles
  # List Business Profiles
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [BusinessProfilesListResponse]
  describe 'list_business_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_business_profile
  # Update Business Profile
  # @param business_profile_id 
  # @param business_profile_patch 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [BusinessProfileResponse]
  describe 'update_business_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
