=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::CustomersApi)
    end
  end

  # unit tests for create_customer_api_v1_customers_post
  # Create Customer
  # @param customer_create 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [CustomerResponse]
  describe 'create_customer_api_v1_customers_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_customer_api_v1_customers_customer_id_delete
  # Delete Customer
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_customer_api_v1_customers_customer_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_customer_api_v1_customers_customer_id_get
  # Get Customer
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'get_customer_api_v1_customers_customer_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_customers_api_v1_customers_get
  # List Customers
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [CustomersListResponse]
  describe 'list_customers_api_v1_customers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_customer_api_v1_customers_customer_id_patch
  # Patch Customer
  # @param customer_id 
  # @param customer_patch 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [CustomerResponse]
  describe 'patch_customer_api_v1_customers_customer_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
