=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::CustomersApi)
    end
  end

  # unit tests for create_customer
  # Create Customer
  # Store a customer you can bill repeatedly.  &#x60;tax_id&#x60; and &#x60;electronic_address&#x60; are what e-invoicing needs: a buyer VAT number and the Peppol identifier a receiver is addressed by. Neither is required for a plain PDF.
  # @param customer_create 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [CustomerResponse]
  describe 'create_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_customer
  # Delete Customer
  # Remove a customer.  &#x60;409&#x60; if any document still references them, naming what does. History is kept rather than rewritten.
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_customer
  # Get Customer
  # One stored customer.
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'get_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_customers
  # List Customers
  # The people and companies you bill, newest first.  Cursor-paginated. A customer is optional — the stateless render endpoints take a buyer inline — but storing one lets a document reference it by id.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [CustomersListResponse]
  describe 'list_customers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_customer
  # Update Customer
  # Change a stored customer.  Only the fields you send are changed — omit one to leave it alone, send &#x60;null&#x60; to clear it. Documents already issued keep the details they were issued with; this does not rewrite them.
  # @param customer_id 
  # @param customer_patch 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [CustomerResponse]
  describe 'update_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
