=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::DocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentsApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::DocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentsApi' do
    it 'should create an instance of DocumentsApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::DocumentsApi)
    end
  end

  # unit tests for archive_document
  # Archive Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'archive_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for calculate_document
  # Calculate Document
  # @param document_calculate_request 
  # @param [Hash] opts the optional parameters
  # @return [DocumentCalculateResponse]
  describe 'calculate_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_document
  # Create Document
  # @param document_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [DocumentResponse]
  describe 'create_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_document_render
  # Create Document Render
  # @param document_id 
  # @param document_render_options 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [RenderResponse]
  describe 'create_document_render test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_document
  # Delete Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for download_document_xml
  # Download Document Xml
  # The e-invoicing XML for a document already stored here.  Reads &#x60;data_json&#x60; directly rather than going through the render path&#39;s reconstruction: the status, the logo and the source document&#39;s number are all attached there for the *PDF*, and none of them belong in the XML. The credit note&#39;s BG-3 reference is already in the stored payload, resolved when the document was written.
  # @param document_id 
  # @param profile Which ruleset to write this against. No default: a document valid under one can be rejected by another, so the choice is the request.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_document_xml test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duplicate_document
  # Duplicate Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'duplicate_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for finalize_document
  # Finalize Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'finalize_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_document
  # Get Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'get_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_document_deliveries
  # List Document Deliveries
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [DeliveriesListResponse]
  describe 'list_document_deliveries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_documents
  # List Documents
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @option opts [String] :document_type 
  # @option opts [String] :status 
  # @return [DocumentsListResponse]
  describe 'list_documents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_paid
  # Mark Paid
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'mark_paid test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_sent
  # Mark Sent
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'mark_sent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_unpaid
  # Mark Unpaid
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'mark_unpaid test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for render_document
  # Render Document
  # @param document_render_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [RenderResponse]
  describe 'render_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for render_document_xml
  # Render Document Xml
  # The e-invoicing XML for a document, without storing anything.  Takes the same body as &#x60;/validate-compliance&#x60;, and the pairing is the point: check first, then take the XML once it passes. Nothing here validates against the ruleset — a document missing mandatory fields serialises to XML missing those elements, which is a more useful artefact to look at than a refusal, and &#x60;/validate-compliance&#x60; is where the refusal belongs.  The syntax is not a parameter. It follows from the profile, because a profile already is a syntax plus a ruleset, and asking a caller for both is asking them to know that Peppol means UBL.
  # @param document_compliance_request 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'render_document_xml test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restore_document
  # Restore Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'restore_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_document
  # Send Document
  # @param document_id 
  # @param delivery_send_request 
  # @param [Hash] opts the optional parameters
  # @return [DeliveryResponse]
  describe 'send_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_document
  # Update Document
  # @param document_id 
  # @param document_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'update_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_compliance
  # Validate Compliance
  # Check a document against an e-invoicing ruleset without rendering it.  Costs no renders: nothing is stored and no PDF is produced, so a caller can check every invoice they are about to send rather than discovering the problem from a rejection weeks later.  Two tiers run, and both are reported. The mandatory-field check names a field of the request you can go and change. Schematron then serializes the document and runs the **published rules at a pinned version** over the result — the same artefacts an access point runs — so a finding here quotes the rule id a rejection notice would quote.  Read &#x60;valid&#x60; together with &#x60;fully_checked&#x60;: &#x60;valid&#x60; says nothing fatal was found, and &#x60;rulesets&#x60; says what actually ran to find it.
  # @param document_compliance_request 
  # @param [Hash] opts the optional parameters
  # @return [DocumentComplianceResponse]
  describe 'validate_compliance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_document
  # Validate Document
  # @param document_validate_request 
  # @param [Hash] opts the optional parameters
  # @return [DocumentValidateResponse]
  describe 'validate_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for void_document
  # Void Document
  # @param document_id 
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'void_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
