=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::HealthApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::HealthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthApi' do
    it 'should create an instance of HealthApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::HealthApi)
    end
  end

  # unit tests for health_health_get
  # Health
  # @param [Hash] opts the optional parameters
  # @return [HealthResponse]
  describe 'health_health_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ready_ready_get
  # Ready
  # @param [Hash] opts the optional parameters
  # @return [ReadyResponse]
  describe 'ready_ready_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for version_version_get
  # Version
  # @param [Hash] opts the optional parameters
  # @return [VersionResponse]
  describe 'version_version_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
