=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::ImportsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ImportsApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::ImportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImportsApi' do
    it 'should create an instance of ImportsApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::ImportsApi)
    end
  end

  # unit tests for cancel_import
  # Cancel Import
  # @param import_id 
  # @param [Hash] opts the optional parameters
  # @return [ImportResponse]
  describe 'cancel_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirm_import
  # Confirm Import
  # @param import_id 
  # @param [Hash] opts the optional parameters
  # @return [ImportResponse]
  describe 'confirm_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_import
  # Create Import
  # @param import_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ImportResponse]
  describe 'create_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_import
  # Get Import
  # @param import_id 
  # @param [Hash] opts the optional parameters
  # @return [ImportResponse]
  describe 'get_import test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
