=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::InvoicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvoicesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::InvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicesApi' do
    it 'should create an instance of InvoicesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::InvoicesApi)
    end
  end

  # unit tests for archive_invoice_api_v1_invoices_invoice_id_archive_post
  # Archive Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'archive_invoice_api_v1_invoices_invoice_id_archive_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for calculate_invoice_api_v1_invoices_calculate_post
  # Calculate Invoice
  # @param invoice_draft_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'calculate_invoice_api_v1_invoices_calculate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_invoice_api_v1_invoices_post
  # Create Invoice
  # @param invoice_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [InvoiceResponse]
  describe 'create_invoice_api_v1_invoices_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_invoice_api_v1_invoices_invoice_id_delete
  # Delete Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_invoice_api_v1_invoices_invoice_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duplicate_invoice_api_v1_invoices_invoice_id_duplicate_post
  # Duplicate Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'duplicate_invoice_api_v1_invoices_invoice_id_duplicate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for finalize_invoice_api_v1_invoices_invoice_id_finalize_post
  # Finalize Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [Hash<String, Object>]
  describe 'finalize_invoice_api_v1_invoices_invoice_id_finalize_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_invoice_api_v1_invoices_invoice_id_get
  # Get Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'get_invoice_api_v1_invoices_invoice_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_invoice_deliveries_api_v1_invoices_invoice_id_deliveries_get
  # List Invoice Deliveries
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [DeliveriesListResponse]
  describe 'list_invoice_deliveries_api_v1_invoices_invoice_id_deliveries_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_invoices_api_v1_invoices_get
  # List Invoices
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @option opts [String] :status 
  # @return [InvoicesListResponse]
  describe 'list_invoices_api_v1_invoices_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_paid_api_v1_invoices_invoice_id_mark_paid_post
  # Mark Paid
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'mark_paid_api_v1_invoices_invoice_id_mark_paid_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_sent_api_v1_invoices_invoice_id_mark_sent_post
  # Mark Sent
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'mark_sent_api_v1_invoices_invoice_id_mark_sent_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_unpaid_api_v1_invoices_invoice_id_mark_unpaid_post
  # Mark Unpaid
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'mark_unpaid_api_v1_invoices_invoice_id_mark_unpaid_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_invoice_api_v1_invoices_invoice_id_patch
  # Patch Invoice
  # @param invoice_id 
  # @param invoice_patch_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [InvoiceResponse]
  describe 'patch_invoice_api_v1_invoices_invoice_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for preview_invoice_api_v1_invoices_preview_post
  # Preview Invoice
  # @param invoice_preview_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'preview_invoice_api_v1_invoices_preview_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for render_invoice_api_v1_invoices_invoice_id_renders_post
  # Render Invoice
  # @param invoice_id 
  # @param invoice_render_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [Object]
  describe 'render_invoice_api_v1_invoices_invoice_id_renders_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replace_invoice_api_v1_invoices_invoice_id_put
  # Replace Invoice
  # @param invoice_id 
  # @param invoice_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [InvoiceResponse]
  describe 'replace_invoice_api_v1_invoices_invoice_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restore_invoice_api_v1_invoices_invoice_id_restore_post
  # Restore Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'restore_invoice_api_v1_invoices_invoice_id_restore_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_invoice_api_v1_invoices_invoice_id_send_post
  # Send Invoice
  # @param invoice_id 
  # @param delivery_send_request 
  # @param [Hash] opts the optional parameters
  # @return [DeliveryResponse]
  describe 'send_invoice_api_v1_invoices_invoice_id_send_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_invoice_api_v1_invoices_validate_post
  # Validate Invoice
  # @param invoice_draft_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'validate_invoice_api_v1_invoices_validate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for void_invoice_api_v1_invoices_invoice_id_void_post
  # Void Invoice
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceResponse]
  describe 'void_invoice_api_v1_invoices_invoice_id_void_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
