=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::JobsApi)
    end
  end

  # unit tests for cancel_job_api_v1_jobs_job_id_cancel_post
  # Cancel Job
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [JobResponse]
  describe 'cancel_job_api_v1_jobs_job_id_cancel_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_api_v1_jobs_job_id_get
  # Get Job
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [JobResponse]
  describe 'get_job_api_v1_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retry_job_api_v1_jobs_job_id_retry_post
  # Retry Job
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [JobResponse]
  describe 'retry_job_api_v1_jobs_job_id_retry_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
