=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::NumberingSequencesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NumberingSequencesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::NumberingSequencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NumberingSequencesApi' do
    it 'should create an instance of NumberingSequencesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::NumberingSequencesApi)
    end
  end

  # unit tests for consume_sequence_number
  # Consume Sequence Number
  # Consume and return the next number, incrementing the counter.
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [NumberingNextResponse]
  describe 'consume_sequence_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_sequence
  # Create Sequence
  # Define how a document type&#39;s numbers are built.  A prefix, an optional date pattern, and a zero-padded counter — &#x60;INV-2026-0001&#x60;. &#x60;reset&#x60; decides whether the counter returns to one each year.
  # @param numbering_sequence_create_request 
  # @param [Hash] opts the optional parameters
  # @return [NumberingSequenceResponse]
  describe 'create_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sequence
  # Delete Sequence
  # Remove a numbering scheme.  Documents of that type then need their number supplied explicitly.
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sequence
  # Get Sequence
  # One numbering sequence, including the number it will issue next.
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [NumberingSequenceResponse]
  describe 'get_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sequences
  # List Sequences
  # The numbering schemes that produce document numbers, newest first.  Each names the document type it numbers, so invoices and credit notes can run on separate counters.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [NumberingSequencesListResponse]
  describe 'list_sequences test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for preview_sequence
  # Preview Sequence
  # Show the next number **without consuming it**.  Nothing is claimed, so calling this twice returns the same number and the number stays available. Use &#x60;consume_sequence_number&#x60; to take it.
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [NumberingSequencePreviewResponse]
  describe 'preview_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sequence
  # Update Sequence
  # Change a numbering scheme.  Numbers already issued are not rewritten, so a change takes effect from the next document. Moving the counter backwards can collide with a number already used.
  # @param sequence_id 
  # @param numbering_sequence_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [NumberingSequenceResponse]
  describe 'update_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
