=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::RecurringInvoicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecurringInvoicesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::RecurringInvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecurringInvoicesApi' do
    it 'should create an instance of RecurringInvoicesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::RecurringInvoicesApi)
    end
  end

  # unit tests for cancel_recurring_invoice
  # Cancel Recurring Invoice
  # @param recurring_id 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'cancel_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_recurring_invoice
  # Create Recurring Invoice
  # @param recurring_invoice_create_request 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'create_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_recurring_invoice
  # Get Recurring Invoice
  # @param recurring_id 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'get_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_generated_invoices
  # List Generated Invoices
  # @param recurring_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [InvoicesListResponse]
  describe 'list_generated_invoices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_recurring_invoices
  # List Recurring Invoices
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @option opts [String] :status 
  # @return [RecurringInvoicesListResponse]
  describe 'list_recurring_invoices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pause_recurring_invoice
  # Pause Recurring Invoice
  # @param recurring_id 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'pause_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resume_recurring_invoice
  # Resume Recurring Invoice
  # @param recurring_id 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'resume_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_recurring_invoice
  # Update Recurring Invoice
  # @param recurring_id 
  # @param recurring_invoice_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [RecurringInvoiceResponse]
  describe 'update_recurring_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
