=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::ReferenceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReferenceApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::ReferenceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReferenceApi' do
    it 'should create an instance of ReferenceApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::ReferenceApi)
    end
  end

  # unit tests for list_countries_api_v1_reference_countries_get
  # List Countries
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_countries_api_v1_reference_countries_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_currencies_api_v1_reference_currencies_get
  # List Currencies
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_currencies_api_v1_reference_currencies_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_document_types_api_v1_reference_document_types_get
  # List Document Types
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_document_types_api_v1_reference_document_types_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_locales_api_v1_reference_locales_get
  # List Locales
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_locales_api_v1_reference_locales_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_page_sizes_api_v1_reference_page_sizes_get
  # List Page Sizes
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_page_sizes_api_v1_reference_page_sizes_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_timezones_api_v1_reference_timezones_get
  # List Timezones
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_timezones_api_v1_reference_timezones_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
