=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::RendersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RendersApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::RendersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RendersApi' do
    it 'should create an instance of RendersApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::RendersApi)
    end
  end

  # unit tests for download_render
  # Download Render
  # Fetch the PDF, by signature or by API key.  Two ways in, and the signature is checked *first* — before the row is looked up — so a forged token cannot be used to tell a real render id from an invented one. It also means the token path costs no auth work at all, which matters because this is the one endpoint a browser hits directly.
  # @param render_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :token The signature from this render&#39;s &#x60;download_url&#x60;. Present it and no API key is needed — that is what makes the URL a link. Omit it and the request authenticates normally.
  # @return [File]
  describe 'download_render test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_render
  # Get Render
  # @param render_id 
  # @param [Hash] opts the optional parameters
  # @return [RenderResponse]
  describe 'get_render test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
