=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::TaxRatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxRatesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::TaxRatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxRatesApi' do
    it 'should create an instance of TaxRatesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::TaxRatesApi)
    end
  end

  # unit tests for create_tax_rate
  # Create Tax Rate
  # @param tax_rate_create_request 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateResponse]
  describe 'create_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tax_rate
  # Delete Tax Rate
  # @param tax_rate_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tax_rate
  # Get Tax Rate
  # @param tax_rate_id 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateResponse]
  describe 'get_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tax_rates
  # List Tax Rates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [TaxRatesListResponse]
  describe 'list_tax_rates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tax_rate
  # Update Tax Rate
  # @param tax_rate_id 
  # @param tax_rate_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateResponse]
  describe 'update_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
