=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplatesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::TemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplatesApi' do
    it 'should create an instance of TemplatesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::TemplatesApi)
    end
  end

  # unit tests for create_template
  # Create Template
  # @param template_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'create_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_template
  # Delete Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duplicate_template
  # Duplicate Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'duplicate_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_builtin_template
  # Get Builtin Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplateDetailResponse]
  describe 'get_builtin_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_template
  # Get Custom Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'get_custom_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_template
  # Get Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplateDetailResponse]
  describe 'get_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_templates
  # List Custom Templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [CustomTemplatesListResponse]
  describe 'list_custom_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_templates
  # List Templates
  # @param [Hash] opts the optional parameters
  # @return [TemplatesListResponse]
  describe 'list_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for preview_template
  # Preview Template
  # @param template_id 
  # @param document_render_request 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :version Preview the config this version recorded rather than the template&#39;s current config. Only a custom (&#x60;ctpl_&#x60;) template has versions.
  # @option opts [String] :idempotency_key 
  # @return [RenderResponse]
  describe 'preview_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for publish_template
  # Publish Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'publish_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_template
  # Update Template
  # @param template_id 
  # @param template_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'update_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
