=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplatesApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::TemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplatesApi' do
    it 'should create an instance of TemplatesApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::TemplatesApi)
    end
  end

  # unit tests for create_template_api_v1_templates_custom_post
  # Create Template
  # @param template_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'create_template_api_v1_templates_custom_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_template_api_v1_templates_custom_template_id_delete
  # Delete Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_template_api_v1_templates_custom_template_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duplicate_template_api_v1_templates_custom_template_id_duplicate_post
  # Duplicate Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'duplicate_template_api_v1_templates_custom_template_id_duplicate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_builtin_template_api_v1_templates_builtin_template_id_get
  # Get Builtin Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplateDetailResponse]
  describe 'get_builtin_template_api_v1_templates_builtin_template_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_template_api_v1_templates_custom_template_id_get
  # Get Custom Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'get_custom_template_api_v1_templates_custom_template_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_template_api_v1_templates_template_id_get
  # Get Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [TemplateDetailResponse]
  describe 'get_template_api_v1_templates_template_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_custom_templates_api_v1_templates_custom_get
  # List Custom Templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [CustomTemplatesListResponse]
  describe 'list_custom_templates_api_v1_templates_custom_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_template_api_v1_templates_custom_template_id_patch
  # Patch Template
  # @param template_id 
  # @param template_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'patch_template_api_v1_templates_custom_template_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for preview_template_api_v1_templates_template_id_preview_post
  # Preview Template
  # @param template_id 
  # @param document_render_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :idempotency_key 
  # @return [Object]
  describe 'preview_template_api_v1_templates_template_id_preview_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for publish_template_api_v1_templates_custom_template_id_publish_post
  # Publish Template
  # @param template_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomTemplateResponse]
  describe 'publish_template_api_v1_templates_custom_template_id_publish_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for templates_api_v1_templates_get
  # Templates
  # @param [Hash] opts the optional parameters
  # @return [TemplatesListResponse]
  describe 'templates_api_v1_templates_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
