=begin
#InvoicePDFs

#InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com

The version of the OpenAPI document: 0.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for InvoicePDFs::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = InvoicePDFs::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(InvoicePDFs::WebhooksApi)
    end
  end

  # unit tests for create_webhook_endpoint
  # Create Webhook Endpoint
  # Register a URL to receive events.  The endpoint starts active and begins receiving the events you list.  A signing secret is generated but is **not** returned here. Call &#x60;rotate_webhook_secret&#x60; to obtain one before you can verify signatures.
  # @param webhook_endpoint_create_request 
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe 'create_webhook_endpoint test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_webhook_endpoint
  # Delete Webhook Endpoint
  # Remove an endpoint and its delivery history.  The endpoint&#39;s delivery records are deleted with it, including any still waiting to be retried. To stop deliveries without losing the history, set &#x60;is_active&#x60; to false instead.
  # @param endpoint_id 
  # @param [Hash] opts the optional parameters
  # @return [SimpleBoolResponse]
  describe 'delete_webhook_endpoint test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_webhook_delivery
  # Get Webhook Delivery
  # One webhook delivery by id — an HTTP POST to one of your endpoints.  Not to be confused with &#x60;get_delivery&#x60;, which is an email sent to a customer.
  # @param delivery_id 
  # @param [Hash] opts the optional parameters
  # @return [WebhookDeliveryResponse]
  describe 'get_webhook_delivery test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_webhook_endpoint
  # Get Webhook Endpoint
  # One webhook endpoint by id.
  # @param endpoint_id 
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe 'get_webhook_endpoint test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_webhook_deliveries
  # List Webhook Deliveries
  # Every webhook delivery attempt on the account, newest first.  One row per attempt to POST an event to one of your endpoints, with the HTTP status and attempt count. For emails sent to your customers, see &#x60;get_delivery&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [WebhookDeliveriesListResponse]
  describe 'list_webhook_deliveries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_webhook_endpoints
  # List Webhook Endpoints
  # Every webhook endpoint registered on the account, newest first.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [WebhookEndpointsListResponse]
  describe 'list_webhook_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retry_webhook_delivery
  # Retry Webhook Delivery
  # Send a failed or pending webhook delivery again, immediately.  Resets the attempt counter on the same delivery and dispatches it without waiting for the retry schedule. Failed deliveries are already retried automatically with backoff, so this is for after those are exhausted — or to send a delivery created by &#x60;test_webhook_endpoint&#x60;.  Refused with 409 in any other status. To re-send an email, use &#x60;retry_delivery&#x60;.
  # @param delivery_id 
  # @param [Hash] opts the optional parameters
  # @return [WebhookDeliveryResponse]
  describe 'retry_webhook_delivery test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_webhook_secret
  # Rotate Webhook Secret
  # Issue a new signing secret and return it.  This is the only response that contains the secret, so it is also how you obtain the first one after creating an endpoint. The previous secret stops being accepted immediately: signatures computed with it will not verify.
  # @param endpoint_id 
  # @param [Hash] opts the optional parameters
  # @return [WebhookSecretResponse]
  describe 'rotate_webhook_secret test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_webhook_endpoint
  # Test Webhook Endpoint
  # Record a test event against this endpoint.  Creates a &#x60;test&#x60; event and a delivery in &#x60;pending&#x60;, which you can inspect with &#x60;get_webhook_delivery&#x60;.  This call does not send the delivery. Pass the returned delivery id to &#x60;retry_webhook_delivery&#x60; to have it dispatched.
  # @param endpoint_id 
  # @param [Hash] opts the optional parameters
  # @return [WebhookDeliveryResponse]
  describe 'test_webhook_endpoint test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_webhook_endpoint
  # Update Webhook Endpoint
  # Change an endpoint&#39;s URL, description, event list or active flag.  Only the fields you send are changed. Setting &#x60;is_active&#x60; to false stops new deliveries while keeping the endpoint and its history, which is the reversible alternative to deleting it.
  # @param endpoint_id 
  # @param webhook_endpoint_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [WebhookEndpointResponse]
  describe 'update_webhook_endpoint test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
