=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for InvoicePDFs::NumberingSequenceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe InvoicePDFs::NumberingSequenceResponse do
  let(:instance) { InvoicePDFs::NumberingSequenceResponse.new }

  describe 'test an instance of NumberingSequenceResponse' do
    it 'should create an instance of NumberingSequenceResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(InvoicePDFs::NumberingSequenceResponse)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
