=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for InvoicePDFs::UsageRenders
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe InvoicePDFs::UsageRenders do
  let(:instance) { InvoicePDFs::UsageRenders.new }

  describe 'test an instance of UsageRenders' do
    it 'should create an instance of UsageRenders' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(InvoicePDFs::UsageRenders)
    end
  end

  describe 'test attribute "used"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "quota"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
