=begin
#InvoicePDFs

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for InvoicePDFs::WorkspaceMemberPatchRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe InvoicePDFs::WorkspaceMemberPatchRequest do
  let(:instance) { InvoicePDFs::WorkspaceMemberPatchRequest.new }

  describe 'test an instance of WorkspaceMemberPatchRequest' do
    it 'should create an instance of WorkspaceMemberPatchRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(InvoicePDFs::WorkspaceMemberPatchRequest)
    end
  end

  describe 'test attribute "role"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["owner", "admin", "member"])
      # validator.allowable_values.each do |value|
      #   expect { instance.role = value }.not_to raise_error
      # end
    end
  end

end
